# Generated by Django 5.2.14 on 2026-10-01 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email_security_alerts', models.BooleanField(default=True, editable=False)),
                ('email_expense_updates', models.BooleanField(default=True)),
                ('email_group_activity', models.BooleanField(default=True)),
                ('email_settlement_updates', models.BooleanField(default=True)),
                ('email_balance_reminders', models.BooleanField(default=True)),
                ('email_product_news', models.BooleanField(default=False)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(db_index=True, max_length=255)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('subject', models.CharField(max_length=255)),
                ('dedup_key', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('suppressed_dedup', 'Suppressed (Deduplication)'), ('suppressed_preference', 'Suppressed (User Preference)')], db_index=True, default='sent', max_length=32)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['recipient_email', 'event_type', 'sent_at'], name='notificatio_recipie_94de93_idx'), models.Index(fields=['dedup_key', 'status', 'sent_at'], name='notificatio_dedup_k_88d681_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('account_created', 'Account Created'), ('account_verified', 'Account Verified'), ('security_alert', 'Security Alert'), ('password_reset', 'Password Reset'), ('password_changed', 'Password Changed'), ('email_changed', 'Email Changed'), ('member_added', 'Added to Group'), ('member_removed', 'Removed from Group'), ('group_created', 'Group Created'), ('group_deleted', 'Group Deleted'), ('role_changed', 'Ownership/Admin Change'), ('expense_added', 'Expense Added'), ('expense_edited', 'Expense Edited'), ('expense_deleted', 'Expense Deleted'), ('balance_updated', 'Balance Updated'), ('balance_settled', 'Balance Settled'), ('settlement_recorded', 'Settlement Recorded'), ('payment_received', 'Payment Received'), ('payment_recorded', 'Payment Recorded'), ('settlement_reminder', 'Settlement Reminder')], db_index=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_entity_id', models.CharField(blank=True, max_length=64, null=True)),
                ('related_entity_type', models.CharField(blank=True, max_length=64, null=True)),
                ('action_url', models.CharField(blank=True, default='', max_length=255)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'), models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx')],
            },
        ),
    ]
