# Generated by Django 5.2.14 on 2026-10-01 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otptoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=255)),
                ('purpose', models.CharField(choices=[('EMAIL_VERIFICATION', 'Email Verification'), ('PASSWORD_RESET', 'Password Reset'), ('CHANGE_EMAIL', 'Change Email'), ('CHANGE_PASSWORD', 'Change Password')], db_index=True, max_length=32)),
                ('otp_hash', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONSUMED', 'Consumed'), ('EXPIRED', 'Expired'), ('INVALIDATED', 'Invalidated')], db_index=True, default='PENDING', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('pending_name', models.CharField(blank=True, default='', max_length=255)),
                ('pending_password_hash', models.CharField(blank=True, default='', max_length=255)),
                ('new_email', models.EmailField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='OTPToken',
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otprecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='otprecord',
            index=models.Index(fields=['email', 'purpose', 'status'], name='accounts_ot_email_5d3a8d_idx'),
        ),
        migrations.AddIndex(
            model_name='otprecord',
            index=models.Index(fields=['user', 'purpose', 'status'], name='accounts_ot_user_id_97ca48_idx'),
        ),
        migrations.AddIndex(
            model_name='otprecord',
            index=models.Index(fields=['expires_at', 'status'], name='accounts_ot_expires_65ca98_idx'),
        ),
    ]
