# Generated by Django 5.2.14 on 2026-09-30 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount_minor', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sent_settlements', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='groups.group')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='received_settlements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
